# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cirque' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cirque
  pod 'MapboxMaps', '11.3.0'

  target 'CirqueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CirqueUITests' do
    # Pods for testing
  end

end
