import { ImageSourcePropType } from "react-native";

// Map of problem names to their corresponding topo images
const topoImages = {
  // Forestland problems
  'forestland-alcove': require('@/assets/topos/forestland-alcove.jpeg'),
  'forestland-alfalfa-or-spanky': require('@/assets/topos/forestland-alfalfa-or-spanky.jpeg'),
  'forestland-bad-moon-rising': require('@/assets/topos/forestland-bad-moon-rising.jpeg'),
  'forestland-bowl-weevil': require('@/assets/topos/forestland-bowl-weevil.jpeg'),
  'forestland-calcite': require('@/assets/topos/forestland-calcite.jpeg'),
  'forestland-chunky': require('@/assets/topos/forestland-chunky.jpeg'),
  'forestland-cleaver-crack': require('@/assets/topos/forestland-cleaver-crack.jpeg'),
  'forestland-concavity': require('@/assets/topos/forestland-concavity.jpeg'),
  'forestland-cube': require('@/assets/topos/forestland-cube.jpeg'),
  'forestland-cube-crack': require('@/assets/topos/forestland-cube-crack.jpeg'),
  'forestland-dirty-and-deep': require('@/assets/topos/forestland-dirty-and-deep.jpeg'),
  'forestland-dredge': require('@/assets/topos/forestland-dredge.jpeg'),
  'forestland-elfen-magic': require('@/assets/topos/forestland-elfen-magic.jpeg'),
  'forestland-fedge': require('@/assets/topos/forestland-fedge.jpeg'),
  'forestland-feel-the-pinch': require('@/assets/topos/forestland-feel-the-pinch.jpeg'),
  'forestland-gandalf': require('@/assets/topos/forestland-gandalf.jpeg'),
  'forestland-hearthstone': require('@/assets/topos/forestland-hearthstone.jpeg'),
  'forestland-hesitator': require('@/assets/topos/forestland-hesitator.jpeg'),
  'forestland-hobbit': require('@/assets/topos/forestland-hobbit.jpeg'),
  'forestland-lock-and-pop': require('@/assets/topos/forestland-lock-and-pop.jpeg'),
  'forestland-lovage': require('@/assets/topos/forestland-lovage.jpeg'),
  'forestland-moondog': require('@/assets/topos/forestland-moondog.jpeg'),
  'forestland-peep': require('@/assets/topos/forestland-peep.jpeg'),
  'forestland-pentaphobia': require('@/assets/topos/forestland-pentaphobia.jpeg'),
  'forestland-physical': require('@/assets/topos/forestland-physical.jpeg'),
  'forestland-playback': require('@/assets/topos/forestland-playback.jpeg'),
  'forestland-portal-crack': require('@/assets/topos/forestland-portal-crack.jpeg'),
  'forestland-power-steering': require('@/assets/topos/forestland-power-steering.jpeg'),
  'forestland-rail': require('@/assets/topos/forestland-rail.jpeg'),
  'forestland-rainbow': require('@/assets/topos/forestland-rainbow.jpeg'),
  'forestland-real-thing': require('@/assets/topos/forestland-real-thing.jpeg'),
  'forestland-redneck': require('@/assets/topos/forestland-redneck.jpeg'),
  'forestland-runner': require('@/assets/topos/forestland-runner.jpeg'),
  'forestland-scarecrow': require('@/assets/topos/forestland-scarecrow.jpeg'),
  'forestland-scram': require('@/assets/topos/forestland-scram.jpeg'),
  'forestland-slice-of-pie': require('@/assets/topos/forestland-slice-of-pie.jpeg'),
  'forestland-slice-of-tea': require('@/assets/topos/forestland-slice-of-tea.jpeg'),
  'forestland-squeezer': require('@/assets/topos/forestland-squeezer.jpeg'),
  'forestland-sunny-and-steep': require('@/assets/topos/forestland-sunny-and-steep.jpeg'),
  'forestland-sword': require('@/assets/topos/forestland-sword.jpeg'),
  'forestland-tahitian-moon': require('@/assets/topos/forestland-tahitian-moon.jpeg'),
  'forestland-toprope-slab': require('@/assets/topos/forestland-toprope-slab.jpeg'),
  'forestland-toto': require('@/assets/topos/forestland-toto.jpeg'),
  'forestland-tron': require('@/assets/topos/forestland-tron.jpeg'),
  'forestland-two-scoops': require('@/assets/topos/forestland-two-scoops.jpeg'),

  // Straightaways problems
  'straightaways-2001': require('@/assets/topos/straightaways-2001.jpeg'),
  'straightaways-answer-man': require('@/assets/topos/straightaways-answer-man.jpeg'),
  'straightaways-batman': require('@/assets/topos/straightaways-batman.jpeg'),
  'straightaways-bear-hug': require('@/assets/topos/straightaways-bear-hug.jpeg'),
  'straightaways-bok-choy': require('@/assets/topos/straightaways-bok-choy.jpeg'),
  'straightaways-bush-craft': require('@/assets/topos/straightaways-bush-craft.jpeg'),
  'straightaways-dog-named-rehab': require('@/assets/topos/straightaways-dog-named-rehab.jpeg'),
  'straightaways-fat-lip': require('@/assets/topos/straightaways-fat-lip.jpeg'),
  'straightaways-freezer': require('@/assets/topos/straightaways-freezer.jpeg'),
  'straightaways-ice-grip': require('@/assets/topos/straightaways-ice-grip.jpeg'),
  'straightaways-icehouse': require('@/assets/topos/straightaways-icehouse.jpeg'),
  'straightaways-lonely-fish': require('@/assets/topos/straightaways-lonely-fish.jpeg'),
  'straightaways-mftb': require('@/assets/topos/straightaways-mftb.jpeg'),
  'straightaways-millennium': require('@/assets/topos/straightaways-millennium.jpeg'),
  'straightaways-miracle-whip': require('@/assets/topos/straightaways-miracle-whip.jpeg'),
  'straightaways-mothermilker': require('@/assets/topos/straightaways-mothermilker.jpeg'),
  'straightaways-mountain-man': require('@/assets/topos/straightaways-mountain-man.jpeg'),
  'straightaways-old-school': require('@/assets/topos/straightaways-old-school.jpeg'),
  'straightaways-pony-ride': require('@/assets/topos/straightaways-pony-ride.jpeg'),
  'straightaways-straightaways-bush-craft': require('@/assets/topos/straightaways-straightaways-bush-craft.jpeg'),
  'straightaways-taller': require('@/assets/topos/straightaways-taller.jpeg'),
  'straightaways-tampax-arete': require('@/assets/topos/straightaways-tampax-arete.jpeg'),
  'straightaways-was': require('@/assets/topos/straightaways-was.jpeg'),

  // Swiftwater problems
  'swiftwater-14-years': require('@/assets/topos/swiftwater-14-years.jpeg'),
  'swiftwater-bam': require('@/assets/topos/swiftwater-bam.jpeg'),
  'swiftwater-balance-step': require('@/assets/topos/swiftwater-balance-step.jpeg'),
  'swiftwater-barista': require('@/assets/topos/swiftwater-barista.jpeg'),
  'swiftwater-bubbles': require('@/assets/topos/swiftwater-bubbles.jpeg'),
  'swiftwater-chicken-man': require('@/assets/topos/swiftwater-chicken-man.jpeg'),
  'swiftwater-dark-days': require('@/assets/topos/swiftwater-dark-days.jpeg'),
  'swiftwater-devonian': require('@/assets/topos/swiftwater-devonian.jpeg'),
  'swiftwater-footless-traverse': require('@/assets/topos/swiftwater-footless-traverse.jpeg'),
  'swiftwater-hate-monger': require('@/assets/topos/swiftwater-hate-monger.jpeg'),
  'swiftwater-heel-hook-rock': require('@/assets/topos/swiftwater-heel-hook-rock.jpeg'),
  'swiftwater-jump': require('@/assets/topos/swiftwater-jump.jpeg'),
  'swiftwater-joels-slab': require('@/assets/topos/swiftwater-joels-slab.jpeg'),
  'swiftwater-lead-pants': require('@/assets/topos/swiftwater-lead-pants.jpeg'),
  'swiftwater-little-guy': require('@/assets/topos/swiftwater-little-guy.jpeg'),
  'swiftwater-lowe-rider': require('@/assets/topos/swiftwater-lowe-rider.jpeg'),
  'swiftwater-lowe-rider-ridge': require('@/assets/topos/swiftwater-lowe-rider-ridge.jpeg'),
  'swiftwater-mickey': require('@/assets/topos/swiftwater-mickey.jpeg'),
  'swiftwater-minnie': require('@/assets/topos/swiftwater-minnie.jpeg'),
  'swiftwater-oceanfront': require('@/assets/topos/swiftwater-oceanfront.jpeg'),
  'swiftwater-pit': require('@/assets/topos/swiftwater-pit.jpeg'),
  'swiftwater-pod-racer': require('@/assets/topos/swiftwater-pod-racer.jpeg'),
  'swiftwater-premium-coffee': require('@/assets/topos/swiftwater-premium-coffee.jpeg'),
  'swiftwater-red': require('@/assets/topos/swiftwater-red.jpeg'),
  'swiftwater-ripple-effect': require('@/assets/topos/swiftwater-ripple-effect.jpeg'),
  'swiftwater-royal-flush': require('@/assets/topos/swiftwater-royal-flush.jpeg'),
  'swiftwater-schist-cave': require('@/assets/topos/swiftwater-schist-cave.jpeg'),
  'swiftwater-schist-crack': require('@/assets/topos/swiftwater-schist-crack.jpeg'),
  'swiftwater-schisthead': require('@/assets/topos/swiftwater-schisthead.jpeg'),
  'swiftwater-sitting-bull': require('@/assets/topos/swiftwater-sitting-bull.jpeg'),
  'swiftwater-squatter': require('@/assets/topos/swiftwater-squatter.jpeg'),
  'swiftwater-transverse': require('@/assets/topos/swiftwater-transverse.jpeg'),
  'swiftwater-whelmed': require('@/assets/topos/swiftwater-whelmed.jpeg'),
} as const;

type TopoImageKey = keyof typeof topoImages;

export function getTopoImage(key: string | undefined): ImageSourcePropType | undefined {
  if (!key) return undefined;
  return topoImages[key as TopoImageKey];
} 