import { ImageSourcePropType } from "react-native";

// Map of problem names to their corresponding topo images
const topoImages = {
  // Forestland problems
  'forestland-alfalfa-or-spanky': require('@/assets/topos/forestland_alfalfa_or_spanky.jpeg'),
  'forestland-bad-moon-rising': require('@/assets/topos/forestland_bad_moon_rising.jpeg'),
  'forestland-bowl-weevil': require('@/assets/topos/forestland_bowl_weevil.jpeg'),
  'forestland-calcite': require('@/assets/topos/forestland_calcite.jpeg'),
  'forestland-chunky': require('@/assets/topos/forestland_chunky.jpeg'),
  'forestland-cleaver-crack': require('@/assets/topos/forestland_cleaver_crack.jpeg'),
  'forestland-concavity': require('@/assets/topos/forestland_concavity.jpeg'),
  'forestland-cube': require('@/assets/topos/forestland_cube.jpeg'),
  'forestland-cube-crack': require('@/assets/topos/forestland_cube_crack.jpeg'),
  'forestland-dirty-and-deep': require('@/assets/topos/forestland_dirty_and_deep.jpeg'),
  'forestland-dredge': require('@/assets/topos/forestland_dredge.jpeg'),
  'forestland-elfen-magic': require('@/assets/topos/forestland_elfen_magic.jpeg'),
  'forestland-fedge': require('@/assets/topos/forestland_fedge.jpeg'),
  'forestland-feel-the-pinch': require('@/assets/topos/forestland_feel_the_pinch.jpeg'),
  'forestland-gandalf': require('@/assets/topos/forestland_gandalf.jpeg'),
  'forestland-hearthstone': require('@/assets/topos/forestland_hearthstone.jpeg'),
  'forestland-hesitator': require('@/assets/topos/forestland_hesitator.jpeg'),
  'forestland-hobbit': require('@/assets/topos/forestland_hobbit.jpeg'),
  'forestland-lock-and-pop': require('@/assets/topos/forestland_lock_and_pop.jpeg'),
  'forestland-lovage': require('@/assets/topos/forestland_lovage.jpeg'),
  'forestland-moondog': require('@/assets/topos/forestland_moondog.jpeg'),
  'forestland-peep': require('@/assets/topos/forestland_peep.jpeg'),
  'forestland-pentaphobia': require('@/assets/topos/forestland_pentaphobia.jpeg'),
  'forestland-physical': require('@/assets/topos/forestland_physical.jpeg'),
  'forestland-playback': require('@/assets/topos/forestland_playback.jpeg'),
  'forestland-portal-crack': require('@/assets/topos/forestland_portal_crack.jpeg'),
  'forestland-power-steering': require('@/assets/topos/forestland_power_steering.jpeg'),
  'forestland-rail': require('@/assets/topos/forestland_rail.jpeg'),
  'forestland-rainbow': require('@/assets/topos/forestland_rainbow.jpeg'),
  'forestland-real-thing': require('@/assets/topos/forestland_real_thing.jpeg'),
  'forestland-redneck': require('@/assets/topos/forestland_redneck.jpeg'),
  'forestland-runner': require('@/assets/topos/forestland_runner.jpeg'),
  'forestland-scarecrow': require('@/assets/topos/forestland_scarecrow.jpeg'),
  'forestland-scram': require('@/assets/topos/forestland_scram.jpeg'),
  'forestland-slice-of-pie': require('@/assets/topos/forestland_slice_of_pie.jpeg'),
  'forestland-slice-of-tea': require('@/assets/topos/forestland_slice_of_tea.jpeg'),
  'forestland-squeezer': require('@/assets/topos/forestland_squeezer.jpeg'),
  'forestland-sunny-and-steep': require('@/assets/topos/forestland_sunny_and_steep.jpeg'),
  'forestland-sword': require('@/assets/topos/forestland_sword.jpeg'),
  'forestland-tahitian-moon': require('@/assets/topos/forestland_tahitian_moon.jpeg'),
  'forestland-toprope-slab': require('@/assets/topos/forestland_toprope_slab.jpeg'),
  'forestland-toto': require('@/assets/topos/forestland_toto.jpeg'),
  'forestland-tron': require('@/assets/topos/forestland_tron.jpeg'),
  'forestland-two-scoops': require('@/assets/topos/forestland_two_scoops.jpeg'),

  // Straightaways problems
  'straightaways-2001': require('@/assets/topos/straightaways_2001.jpeg'),
  'straightaways-answer-man': require('@/assets/topos/straightaways_answer_man.jpeg'),
  'straightaways-batman': require('@/assets/topos/straightaways_batman.jpeg'),
  'straightaways-bear-hug': require('@/assets/topos/straightaways_bear_hug.jpeg'),
  'straightaways-bok-choy': require('@/assets/topos/straightaways_bok_choy.jpeg'),
  'straightaways-bush-craft': require('@/assets/topos/straightaways_bush_craft.jpeg'),
  'straightaways-dog-named-rehab': require('@/assets/topos/straightaways_dog_named_rehab.jpeg'),
  'straightaways-fat-lip': require('@/assets/topos/straightaways_fat_lip.jpeg'),
  'straightaways-freezer': require('@/assets/topos/straightaways_freezer.jpeg'),
  'straightaways-ice-grip': require('@/assets/topos/straightaways_ice_grip.jpeg'),
  'straightaways-icehouse': require('@/assets/topos/straightaways_icehouse.jpeg'),
  'straightaways-lonely-fish': require('@/assets/topos/straightaways_lonely_fish.jpeg'),
  'straightaways-mftb': require('@/assets/topos/straightaways_mftb.jpeg'),
  'straightaways-millennium': require('@/assets/topos/straightaways_millennium.jpeg'),
  'straightaways-miracle-whip': require('@/assets/topos/straightaways_miracle_whip.jpeg'),
  'straightaways-mountain-man': require('@/assets/topos/straightaways_mountain_man.jpeg'),
  'straightaways-old-school': require('@/assets/topos/straightaways_old_school.jpeg'),
  'straightaways-pony-ride': require('@/assets/topos/straightaways_pony_ride.jpeg'),
  'straightaways-straightaways-bush-craft': require('@/assets/topos/straightaways_straightaways_bush_craft.jpeg'),
  'straightaways-taller': require('@/assets/topos/straightaways_taller.jpeg'),
  'straightaways-tampax-arete': require('@/assets/topos/straightaways_tampax_arete.jpeg'),
  'straightaways-was': require('@/assets/topos/straightaways_was.jpeg'),

  // Swiftwater problems
  'swiftwater-14-years': require('@/assets/topos/swiftwater_14_years.jpeg'),
  'swiftwater-balance-step': require('@/assets/topos/swiftwater_balance_step.jpeg'),
  'swiftwater-barista': require('@/assets/topos/swiftwater_barista.jpeg'),
  'swiftwater-bubbles': require('@/assets/topos/swiftwater_bubbles.jpeg'),
  'swiftwater-chicken-man': require('@/assets/topos/swiftwater_chicken_man.jpeg'),
  'swiftwater-dark-days': require('@/assets/topos/swiftwater_dark_days.jpeg'),
  'swiftwater-devonian': require('@/assets/topos/swiftwater_devonian.jpeg'),
  'swiftwater-footless-traverse': require('@/assets/topos/swiftwater_footless_traverse.jpeg'),
  'swiftwater-hate-monger': require('@/assets/topos/swiftwater_hate_monger.jpeg'),
  'swiftwater-heel-hook-rock': require('@/assets/topos/swiftwater_heel_hook_rock.jpeg'),
  'swiftwater-lowe-rider': require('@/assets/topos/swiftwater_lowe_rider.jpeg'),
  'swiftwater-mickey': require('@/assets/topos/swiftwater_mickey.jpeg'),
  'swiftwater-minnie': require('@/assets/topos/swiftwater_minnie.jpeg'),
  'swiftwater-oceanfront': require('@/assets/topos/swiftwater_oceanfront.jpeg'),
  'swiftwater-pod-racer': require('@/assets/topos/swiftwater_pod_racer.jpeg'),
  'swiftwater-premium-coffee': require('@/assets/topos/swiftwater_premium_coffee.jpeg'),
  'swiftwater-red': require('@/assets/topos/swiftwater_red.jpeg'),
  'swiftwater-ripple-effect': require('@/assets/topos/swiftwater_ripple_effect.jpeg'),
  'swiftwater-royal-flush': require('@/assets/topos/swiftwater_royal_flush.jpeg'),
  'swiftwater-schist-cave': require('@/assets/topos/swiftwater_schist_cave.jpeg'),
  'swiftwater-schist-crack': require('@/assets/topos/swiftwater_schist_crack.jpeg'),
  'swiftwater-schisthead': require('@/assets/topos/swiftwater_schisthead.jpeg'),
  'swiftwater-sitting-bull': require('@/assets/topos/swiftwater_sitting_bull.jpeg'),
  'swiftwater-squatter': require('@/assets/topos/swiftwater_squatter.jpeg'),
  'swiftwater-transverse': require('@/assets/topos/swiftwater_transverse.jpeg'),
  'swiftwater-whelmed': require('@/assets/topos/swiftwater_whelmed.jpeg'),
} as const;

type TopoImageKey = keyof typeof topoImages;

export function getTopoImage(key: string | undefined): ImageSourcePropType | undefined {
  if (!key) return undefined;
  return topoImages[key as TopoImageKey];
} 