name: Test

on:
  pull_request:
    paths:
      - "react-native/**"

jobs:
  lint:
    uses: ./.github/workflows/node-template.yml
    with:
      command: lint

  format:
    uses: ./.github/workflows/node-template.yml
    with:
      command: format:check

  typecheck:
    uses: ./.github/workflows/node-template.yml
    with:
      command: typecheck

  build:
    needs: typecheck
    uses: ./.github/workflows/node-template.yml
    with:
      command: expo export --platform android --output-dir dist --clear
