name: Test

on:
  push:
    paths:
      - "react-native/**"

jobs:
  lint:
    uses: ./.github/workflows/node-template.yml
    with:
      command: lint
      path: react-native

  format:
    uses: ./.github/workflows/node-template.yml
    with:
      command: format:check
      path: react-native

  typecheck:
    uses: ./.github/workflows/node-template.yml
    with:
      command: typecheck
      path: react-native
